# Generated by Django 2.2.5 on 2020-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200523_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción de la Tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
